#!/usr/bin/env python3
"""
Council Command Center - Dashboard Sync

Reads all state files and generates dashboard/data.js
Run this after any state change to keep dashboard current.
"""

import json
import os
from pathlib import Path
from datetime import datetime

# Import state functions
from update_state import get_dashboard_data, _now_iso

# Paths
COUNCIL_DIR = Path(__file__).parent.parent
DASHBOARD_DIR = COUNCIL_DIR.parent / "dashboard"
DATA_JS_FILE = DASHBOARD_DIR / "data.js"


def sync_dashboard() -> dict:
    """
    Sync state to dashboard/data.js
    
    Returns:
        The synced data
    """
    # Get merged state
    data = get_dashboard_data()
    
    # Ensure dashboard directory exists
    DASHBOARD_DIR.mkdir(exist_ok=True)
    
    # Generate JavaScript module format
    js_content = f"""// Auto-generated by sync_dashboard.py
// Last sync: {_now_iso()}
// DO NOT EDIT MANUALLY

window.COUNCIL_DATA = {json.dumps(data, indent=2)};

// For ES module compatibility
if (typeof module !== 'undefined') {{
  module.exports = window.COUNCIL_DATA;
}}
"""
    
    # Write to data.js
    with open(DATA_JS_FILE, 'w') as f:
        f.write(js_content)
    
    print(f"✅ Synced dashboard data to {DATA_JS_FILE}")
    print(f"   Balance: ${data['balance']} / ${data['target']} ({data['progress']}%)")
    print(f"   Pipeline: {sum(data['pipelineCounts'].values())} opportunities")
    print(f"   Feed entries: {len(data['feed'])}")
    
    return data


def generate_html_fallback() -> None:
    """
    Generate a simple HTML dashboard if the main one doesn't exist.
    """
    index_file = DASHBOARD_DIR / "index.html"
    
    if index_file.exists():
        return
    
    html = """<!DOCTYPE html>
<html>
<head>
    <title>Council Command Center</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
        * { box-sizing: border-box; margin: 0; padding: 0; }
        body { 
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            background: linear-gradient(135deg, #1a1a2e 0%, #16213e 100%);
            color: #eee;
            min-height: 100vh;
            padding: 20px;
        }
        .container { max-width: 1200px; margin: 0 auto; }
        h1 { 
            text-align: center; 
            margin-bottom: 30px;
            background: linear-gradient(45deg, #00d4ff, #7c3aed);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
        }
        .stats { 
            display: grid; 
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); 
            gap: 20px;
            margin-bottom: 30px;
        }
        .stat-card {
            background: rgba(255,255,255,0.05);
            border: 1px solid rgba(255,255,255,0.1);
            border-radius: 12px;
            padding: 20px;
            text-align: center;
        }
        .stat-value { font-size: 2rem; font-weight: bold; color: #00d4ff; }
        .stat-label { color: #888; margin-top: 5px; }
        .progress-bar {
            background: rgba(255,255,255,0.1);
            border-radius: 10px;
            height: 20px;
            overflow: hidden;
            margin: 20px 0;
        }
        .progress-fill {
            height: 100%;
            background: linear-gradient(90deg, #00d4ff, #7c3aed);
            transition: width 0.5s ease;
        }
        .feed {
            background: rgba(255,255,255,0.05);
            border: 1px solid rgba(255,255,255,0.1);
            border-radius: 12px;
            padding: 20px;
        }
        .feed h2 { margin-bottom: 15px; }
        .feed-item {
            padding: 10px 0;
            border-bottom: 1px solid rgba(255,255,255,0.05);
            display: flex;
            gap: 10px;
        }
        .feed-item:last-child { border-bottom: none; }
        .feed-time { color: #666; font-size: 0.8rem; min-width: 80px; }
        .feed-agent { 
            background: #7c3aed33; 
            padding: 2px 8px; 
            border-radius: 4px; 
            font-size: 0.8rem;
            min-width: 70px;
            text-align: center;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>⚡ Council Command Center</h1>
        
        <div class="stats">
            <div class="stat-card">
                <div class="stat-value" id="balance">$--</div>
                <div class="stat-label">Current Balance</div>
            </div>
            <div class="stat-card">
                <div class="stat-value" id="target">$--</div>
                <div class="stat-label">Target</div>
            </div>
            <div class="stat-card">
                <div class="stat-value" id="progress">--%</div>
                <div class="stat-label">Progress</div>
            </div>
            <div class="stat-card">
                <div class="stat-value" id="pipeline">--</div>
                <div class="stat-label">In Pipeline</div>
            </div>
        </div>
        
        <div class="progress-bar">
            <div class="progress-fill" id="progress-bar" style="width: 0%"></div>
        </div>
        
        <div class="feed">
            <h2>📡 Activity Feed</h2>
            <div id="feed-list">Loading...</div>
        </div>
    </div>
    
    <script src="data.js"></script>
    <script>
        function render() {
            const d = window.COUNCIL_DATA;
            if (!d) { console.error('No data'); return; }
            
            document.getElementById('balance').textContent = '$' + d.balance.toLocaleString();
            document.getElementById('target').textContent = '$' + d.target.toLocaleString();
            document.getElementById('progress').textContent = d.progress + '%';
            document.getElementById('progress-bar').style.width = Math.min(d.progress, 100) + '%';
            
            const pipelineTotal = Object.values(d.pipelineCounts).reduce((a,b) => a+b, 0);
            document.getElementById('pipeline').textContent = pipelineTotal;
            
            const feedHtml = d.feed.slice(0, 10).map(e => `
                <div class="feed-item">
                    <span class="feed-time">${new Date(e.timestamp).toLocaleTimeString()}</span>
                    <span class="feed-agent">${e.agent}</span>
                    <span>${e.icon} ${e.message}</span>
                </div>
            `).join('');
            document.getElementById('feed-list').innerHTML = feedHtml || '<p>No activity yet</p>';
        }
        render();
    </script>
</body>
</html>
"""
    
    with open(index_file, 'w') as f:
        f.write(html)
    
    print(f"✅ Generated fallback dashboard at {index_file}")


if __name__ == "__main__":
    import sys
    
    # Sync state to dashboard
    sync_dashboard()
    
    # Generate fallback HTML if needed
    if "--with-html" in sys.argv:
        generate_html_fallback()
