// Auto-generated by sync_dashboard.py
// Last sync: 2026-02-06T23:22:04.567940Z

const DASHBOARD_DATA = {
  "balance": 500,
  "target": 2399,
  "progress": 20.8,
  "startDate": "2026-02-04",
  "lastUpdate": "2026-02-06T23:22:04.567940Z",
  "agents": {
    "scanner": {
      "status": "active",
      "lastScan": "2026-02-06T23:10:54.490068Z",
      "scansToday": 0,
      "hitsToday": 4
    },
    "research": {
      "status": "idle",
      "lastTask": "Awaiting opportunities",
      "queueCount": 4
    }
  },
  "income": {
    "freelance": 0,
    "trading": 0,
    "other": 0
  },
  "opportunities": [
    {
      "id": "nvda-20260206",
      "name": "NVDA GAP_UP +7.9%",
      "type": "trade",
      "amount": 118,
      "stage": "ready",
      "createdAt": "2026-02-06T23:10:54.490068Z",
      "recommendation": "BUY_DIP",
      "confidence": "high",
      "thesis": {
        "bull_case": "Strong momentum with 7.9% move. Gap up signals strong buyer interest",
        "bear_case": "Extended move may need consolidation. Gaps often partially fill - wait for pullback",
        "risk_reward": "2.0:1",
        "entry": 181.7,
        "stop_loss": 172.62,
        "target": 199.87,
        "support": 171.03,
        "resistance": 190.3
      }
    },
    {
      "id": "amd-20260206",
      "name": "AMD GAP_UP +8.3%",
      "type": "trade",
      "amount": 124,
      "stage": "ready",
      "createdAt": "2026-02-06T23:10:54.490068Z",
      "recommendation": "BUY_DIP",
      "confidence": "medium",
      "thesis": {
        "bull_case": "Strong momentum with 8.3% move. Gap up signals strong buyer interest",
        "bear_case": "Extended move may need consolidation. Gaps often partially fill - wait for pullback",
        "risk_reward": "2.0:1",
        "entry": 204.27,
        "stop_loss": 194.06,
        "target": 224.7,
        "support": 190.72,
        "resistance": 252.65
      }
    },
    {
      "id": "pltr-20260206",
      "name": "PLTR GAP_UP +4.5%",
      "type": "trade",
      "amount": 67,
      "stage": "ready",
      "createdAt": "2026-02-06T23:10:54.490068Z",
      "recommendation": "BUY_DIP",
      "confidence": "medium",
      "thesis": {
        "bull_case": "Healthy momentum at 4.5%. Gap up signals strong buyer interest",
        "bear_case": "Low volume (0.7x avg) suggests weak conviction. Gaps often partially fill - wait for pullback",
        "risk_reward": "2.0:1",
        "entry": 133.18,
        "stop_loss": 126.52,
        "target": 146.5,
        "support": 128.32,
        "resistance": 165.08
      }
    },
    {
      "id": "smci-20260206",
      "name": "SMCI GAP_UP +11.4%",
      "type": "trade",
      "amount": 171,
      "stage": "ready",
      "createdAt": "2026-02-06T23:10:54.490068Z",
      "recommendation": "BUY_DIP",
      "confidence": "medium",
      "thesis": {
        "bull_case": "Strong momentum with 11.4% move. Gap up signals strong buyer interest. Trading near highs shows strength",
        "bear_case": "Extended move may need consolidation. Gaps often partially fill - wait for pullback. Near resistance - may face selling pressure",
        "risk_reward": "2.0:1",
        "entry": 33.69,
        "stop_loss": 32.01,
        "target": 37.06,
        "support": 28.64,
        "resistance": 34.94
      }
    }
  ],
  "feed": [
    {
      "timestamp": "2026-02-06T23:04:59.778112Z",
      "agent": "research",
      "icon": "\ud83d\udcc8",
      "message": "Analyzed SMCI: BUY_DIP recommendation (2.0:1 R/R)"
    },
    {
      "timestamp": "2026-02-06T23:04:59.697314Z",
      "agent": "research",
      "icon": "\ud83d\udcc8",
      "message": "Analyzed PLTR: BUY_DIP recommendation (2.0:1 R/R)"
    },
    {
      "timestamp": "2026-02-06T23:04:59.615993Z",
      "agent": "research",
      "icon": "\ud83d\udcc8",
      "message": "Analyzed AMD: BUY_DIP recommendation (2.0:1 R/R)"
    },
    {
      "timestamp": "2026-02-06T23:04:59.529934Z",
      "agent": "research",
      "icon": "\ud83d\udcc8",
      "message": "Analyzed NVDA: BUY_DIP recommendation (2.0:1 R/R)"
    },
    {
      "timestamp": "2026-02-06T23:03:00.144116Z",
      "agent": "research",
      "icon": "\u2705",
      "message": "Research complete: 4 trades, 0 gigs analyzed"
    },
    {
      "timestamp": "2026-02-06T23:03:00.143076Z",
      "agent": "research",
      "icon": "\ud83d\udcc8",
      "message": "Analyzed SMCI: BUY_DIP recommendation (2.0:1 R/R)"
    },
    {
      "timestamp": "2026-02-06T23:03:00.060246Z",
      "agent": "research",
      "icon": "\ud83d\udcc8",
      "message": "Analyzed PLTR: BUY_DIP recommendation (2.0:1 R/R)"
    },
    {
      "timestamp": "2026-02-06T23:02:59.974807Z",
      "agent": "research",
      "icon": "\ud83d\udcc8",
      "message": "Analyzed AMD: BUY_DIP recommendation (2.0:1 R/R)"
    },
    {
      "timestamp": "2026-02-06T23:02:59.897345Z",
      "agent": "research",
      "icon": "\ud83d\udcc8",
      "message": "Analyzed NVDA: BUY_DIP recommendation (2.0:1 R/R)"
    },
    {
      "timestamp": "2026-02-06T22:27:00Z",
      "agent": "main",
      "icon": "\ud83d\ude80",
      "message": "Council Command Center initialized"
    }
  ],
  "nextActions": [
    {
      "text": "Review 4 opportunities",
      "done": false
    },
    {
      "text": "Check market status",
      "done": false
    }
  ]
};
