// Auto-generated by sync_dashboard.py
// Last sync: 2026-02-07T01:58:04.616775Z

const DASHBOARD_DATA = {
  "balance": 500,
  "target": 2399,
  "progress": 20.8,
  "startDate": "2026-02-04",
  "lastUpdate": "2026-02-07T01:58:04.616775Z",
  "agents": {
    "scanner": {
      "status": "active",
      "lastScan": "2026-02-07T01:57:10.276453Z",
      "scansToday": 0,
      "hitsToday": 13
    },
    "research": {
      "status": "idle",
      "lastTask": "Awaiting opportunities",
      "queueCount": 16
    }
  },
  "income": {
    "freelance": 0,
    "trading": 0,
    "other": 0
  },
  "opportunities": [
    {
      "id": "nvda-20260207",
      "name": "NVDA GAP_UP +7.9%",
      "type": "trade",
      "amount": 118,
      "stage": "ready",
      "createdAt": "2026-02-07T01:57:10.276453Z",
      "recommendation": "BUY_DIP",
      "confidence": "high",
      "thesis": {
        "bull_case": "Strong momentum with 7.9% move. Gap up signals strong buyer interest",
        "bear_case": "Extended move may need consolidation. Gaps often partially fill - wait for pullback",
        "risk_reward": "2.0:1",
        "entry": 181.7,
        "stop_loss": 172.62,
        "target": 199.87,
        "support": 171.03,
        "resistance": 190.3
      }
    },
    {
      "id": "amd-20260207",
      "name": "AMD GAP_UP +8.3%",
      "type": "trade",
      "amount": 124,
      "stage": "ready",
      "createdAt": "2026-02-07T01:57:10.276453Z",
      "recommendation": "BUY_DIP",
      "confidence": "medium",
      "thesis": {
        "bull_case": "Strong momentum with 8.3% move. Gap up signals strong buyer interest",
        "bear_case": "Extended move may need consolidation. Gaps often partially fill - wait for pullback",
        "risk_reward": "2.0:1",
        "entry": 204.27,
        "stop_loss": 194.06,
        "target": 224.7,
        "support": 190.72,
        "resistance": 252.65
      }
    },
    {
      "id": "pltr-20260207",
      "name": "PLTR GAP_UP +4.5%",
      "type": "trade",
      "amount": 67,
      "stage": "ready",
      "createdAt": "2026-02-07T01:57:10.276453Z",
      "recommendation": "BUY_DIP",
      "confidence": "medium",
      "thesis": {
        "bull_case": "Healthy momentum at 4.5%. Gap up signals strong buyer interest",
        "bear_case": "Low volume (0.7x avg) suggests weak conviction. Gaps often partially fill - wait for pullback",
        "risk_reward": "2.0:1",
        "entry": 133.18,
        "stop_loss": 126.52,
        "target": 146.5,
        "support": 128.32,
        "resistance": 165.08
      }
    },
    {
      "id": "smci-20260207",
      "name": "SMCI GAP_UP +11.4%",
      "type": "trade",
      "amount": 171,
      "stage": "ready",
      "createdAt": "2026-02-07T01:57:10.276453Z",
      "recommendation": "BUY_DIP",
      "confidence": "medium",
      "thesis": {
        "bull_case": "Strong momentum with 11.4% move. Gap up signals strong buyer interest. Trading near highs shows strength",
        "bear_case": "Extended move may need consolidation. Gaps often partially fill - wait for pullback. Near resistance - may face selling pressure",
        "risk_reward": "2.0:1",
        "entry": 33.69,
        "stop_loss": 32.01,
        "target": 37.06,
        "support": 28.64,
        "resistance": 34.94
      }
    },
    {
      "id": "9d2b66a191ef",
      "name": "Scheduled Excel Report Automation",
      "type": "gig",
      "amount": 300,
      "stage": "detected",
      "createdAt": "2026-02-07T01:57:10.276488Z"
    },
    {
      "id": "c5a2a2345f12",
      "name": "",
      "type": "gig",
      "amount": 300,
      "stage": "detected",
      "createdAt": "2026-02-07T01:57:10.276488Z"
    },
    {
      "id": "12199e667299",
      "name": "",
      "type": "gig",
      "amount": 300,
      "stage": "detected",
      "createdAt": "2026-02-07T01:57:10.276488Z"
    },
    {
      "id": "23ed5b80db55",
      "name": "I will make com automation, fix make com",
      "type": "gig",
      "amount": 300,
      "stage": "detected",
      "createdAt": "2026-02-07T01:57:10.276488Z"
    },
    {
      "id": "46cd60092035",
      "name": "I will fix make com error, make com auto",
      "type": "gig",
      "amount": 300,
      "stage": "detected",
      "createdAt": "2026-02-07T01:57:10.276488Z"
    },
    {
      "id": "0df21e936408",
      "name": "",
      "type": "gig",
      "amount": 300,
      "stage": "detected",
      "createdAt": "2026-02-07T01:57:10.276488Z"
    },
    {
      "id": "32919722970b",
      "name": "",
      "type": "gig",
      "amount": 300,
      "stage": "detected",
      "createdAt": "2026-02-07T01:57:10.276488Z"
    },
    {
      "id": "84541418b849",
      "name": "Get the best make com setup services",
      "type": "gig",
      "amount": 300,
      "stage": "detected",
      "createdAt": "2026-02-07T01:57:10.276488Z"
    },
    {
      "id": "d7c12bb7b1fd",
      "name": "Get the best make com services",
      "type": "gig",
      "amount": 300,
      "stage": "detected",
      "createdAt": "2026-02-07T01:57:10.276488Z"
    },
    {
      "id": "opt-nvda-185-20260207",
      "name": "\ud83c\udfb0 NVDA CALLS $185 (2026-)",
      "type": "options",
      "amount": 225,
      "stage": "ready",
      "createdAt": "2026-02-07T01:57:10.276453Z",
      "risk": "MEDIUM",
      "signal": "Big move +7.9% - CALLS play",
      "iv": 0.3178779150390625,
      "underlying_price": 185.41000366210938
    },
    {
      "id": "opt-amd-210-20260207",
      "name": "\ud83c\udfb0 AMD CALLS $210 (2026-)",
      "type": "options",
      "amount": 589,
      "stage": "ready",
      "createdAt": "2026-02-07T01:57:10.276453Z",
      "risk": "HIGH",
      "signal": "Big move +8.3% - CALLS play",
      "iv": 0.5690961059570312,
      "underlying_price": 208.44000244140625
    },
    {
      "id": "opt-smci-35-20260207",
      "name": "\ud83c\udfb0 SMCI CALLS $35 (2026-)",
      "type": "options",
      "amount": 103,
      "stage": "ready",
      "createdAt": "2026-02-07T01:57:10.276453Z",
      "risk": "HIGH",
      "signal": "Big move +11.4% - CALLS play",
      "iv": 0.6796907031250001,
      "underlying_price": 34.380001068115234
    }
  ],
  "feed": [
    {
      "timestamp": "2026-02-06T23:04:59.778112Z",
      "agent": "research",
      "icon": "\ud83d\udcc8",
      "message": "Analyzed SMCI: BUY_DIP recommendation (2.0:1 R/R)"
    },
    {
      "timestamp": "2026-02-06T23:04:59.697314Z",
      "agent": "research",
      "icon": "\ud83d\udcc8",
      "message": "Analyzed PLTR: BUY_DIP recommendation (2.0:1 R/R)"
    },
    {
      "timestamp": "2026-02-06T23:04:59.615993Z",
      "agent": "research",
      "icon": "\ud83d\udcc8",
      "message": "Analyzed AMD: BUY_DIP recommendation (2.0:1 R/R)"
    },
    {
      "timestamp": "2026-02-06T23:04:59.529934Z",
      "agent": "research",
      "icon": "\ud83d\udcc8",
      "message": "Analyzed NVDA: BUY_DIP recommendation (2.0:1 R/R)"
    },
    {
      "timestamp": "2026-02-06T23:03:00.144116Z",
      "agent": "research",
      "icon": "\u2705",
      "message": "Research complete: 4 trades, 0 gigs analyzed"
    },
    {
      "timestamp": "2026-02-06T23:03:00.143076Z",
      "agent": "research",
      "icon": "\ud83d\udcc8",
      "message": "Analyzed SMCI: BUY_DIP recommendation (2.0:1 R/R)"
    },
    {
      "timestamp": "2026-02-06T23:03:00.060246Z",
      "agent": "research",
      "icon": "\ud83d\udcc8",
      "message": "Analyzed PLTR: BUY_DIP recommendation (2.0:1 R/R)"
    },
    {
      "timestamp": "2026-02-06T23:02:59.974807Z",
      "agent": "research",
      "icon": "\ud83d\udcc8",
      "message": "Analyzed AMD: BUY_DIP recommendation (2.0:1 R/R)"
    },
    {
      "timestamp": "2026-02-06T23:02:59.897345Z",
      "agent": "research",
      "icon": "\ud83d\udcc8",
      "message": "Analyzed NVDA: BUY_DIP recommendation (2.0:1 R/R)"
    },
    {
      "timestamp": "2026-02-06T22:27:00Z",
      "agent": "main",
      "icon": "\ud83d\ude80",
      "message": "Council Command Center initialized"
    }
  ],
  "nextActions": [
    {
      "text": "Review 16 opportunities",
      "done": false
    },
    {
      "text": "Check market status",
      "done": false
    }
  ]
};
