// Auto-generated by sync_dashboard.py
// Last sync: 2026-02-06T22:40:13.723975Z

const DASHBOARD_DATA = {
  "balance": 500,
  "target": 2399,
  "startDate": "2026-02-04",
  "lastUpdate": "2026-02-06T22:40:13.723975Z",
  "agents": {
    "scanner": {
      "status": "active",
      "lastScan": "2026-02-06T22:39:18.492374Z",
      "scansToday": 0,
      "hitsToday": 4
    },
    "research": {
      "status": "idle",
      "lastTask": "Awaiting opportunities",
      "queueCount": 4
    }
  },
  "income": {
    "freelance": 0,
    "trading": 0,
    "other": 0
  },
  "opportunities": [
    {
      "id": "nvda-20260206",
      "name": "NVDA GAP_UP +7.9%",
      "type": "trade",
      "amount": 118,
      "stage": "detected",
      "createdAt": "2026-02-06T22:39:18.492374Z"
    },
    {
      "id": "amd-20260206",
      "name": "AMD GAP_UP +8.3%",
      "type": "trade",
      "amount": 124,
      "stage": "detected",
      "createdAt": "2026-02-06T22:39:18.492374Z"
    },
    {
      "id": "pltr-20260206",
      "name": "PLTR GAP_UP +4.5%",
      "type": "trade",
      "amount": 67,
      "stage": "detected",
      "createdAt": "2026-02-06T22:39:18.492374Z"
    },
    {
      "id": "smci-20260206",
      "name": "SMCI GAP_UP +11.4%",
      "type": "trade",
      "amount": 171,
      "stage": "detected",
      "createdAt": "2026-02-06T22:39:18.492374Z"
    }
  ],
  "feed": [
    {
      "timestamp": "2026-02-06T22:27:00Z",
      "agent": "main",
      "icon": "\ud83d\ude80",
      "message": "Council Command Center initialized"
    }
  ],
  "nextActions": [
    "Review 4 opportunities"
  ]
};
